# List Scylla end points

# An example with a single cluster and two DC
- targets:
       - 10.24.79.127:9180
       - 10.24.65.36:9180
       - 10.24.69.9:9180
       - 10.24.67.89:9180
       - 10.24.77.105:9180
  labels:
       cluster: mec-cluster
       dc: dc1
